# Generated by Django 4.0 on 2021-12-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exambase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='year',
            field=models.CharField(default='Sample', max_length=6),
        ),
    ]
