# Generated by Django 4.0 on 2021-12-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exambase', '0002_exam_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='exam_position',
            field=models.PositiveIntegerField(),
        ),
    ]
