# Generated by Django 4.0 on 2021-12-14 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exambase', '0003_alter_question_exam_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_image_path',
        ),
    ]
