# Generated by Django 4.0 on 2022-02-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exambase', '0005_alter_option_options_alter_option_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attempt',
            name='num_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
