# Generated by Django 4.0 on 2022-02-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exambase', '0006_attempt_is_correct_attempt_num_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='year',
            field=models.CharField(default='Sample', max_length=15),
        ),
        migrations.AlterField(
            model_name='option',
            name='option',
            field=models.CharField(max_length=1),
        ),
    ]
