# Generated by Django 4.0 on 2022-02-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exambase', '0008_rename_paper_exam_paper_name_exam_paper_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='exam_position',
            field=models.CharField(max_length=2),
        ),
    ]
