# Generated by Django 4.0 on 2022-02-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exambase', '0009_alter_question_exam_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='paper_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
